server:
  port: 8888
spring:
  application:
    name: gateway-service-zuul

#zuul:
#  routes:
#    api-a:
#      path: /producer/**
#      serviceId: spring-cloud-producer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
